services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: todo_list
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoList-next
    environment: 
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: todo_list
      DATABASE_URL: postgresql://admin:strong_password@db:5432/todo_list
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - db
volumes:
  postgres_data:
   external: true
   name: 6c456ed76b9cff2597a904fc9968220f72c5eb89242a62626faf3c0c2c3c3aa1